---
title: "My Document"
crossref:
  fig-prefix: Figure            # Regular figures
  custom:
    - kind: float
      key: suppfig             # Key for ordering
      reference-prefix: "Supplementary Figure"
    - kind: float
      key: etbl               # Key for ordering
      reference-prefix: "Extended Table"
format:
  html: default
  docx: default
self-contained: true
filters:
  - quarto
  - display-item-order
display-item-order:
  - fig      # Regular figures first
  - etbl     # Extended tables second
  - suppfig  # Supplementary figures last
---

## Introduction

This paper includes regular figures (@fig-main), extended tables (@etbl-data), 
and supplementary figures (@suppfig-additional). Notice the order of the display items in the rendered document is controlled by the `display-item-order` metadata.

```{r}
#| label: fig-main
#| fig-cap: "Main analysis"
#| echo: false
plot(cars)
```

Some text

::: {#suppfig-additional}
```{r}
#| fig-cap: "Supplementary analysis"
#| echo: false
plot(pressure)
```
:::

More text

::: {#etbl-data}
```{r}
#| tbl-cap: "Extended data table"
#| echo: false
pressure
```
:::